{{ config (materialized='table')}}

select
C_CUSTKEY C_CUSTKEY,
C_NAME C_NAME ,
sum(O_TOTALPRICE) TOTALPRICE
from "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER" C
LEFT JOIN  "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."ORDERS"  O ON  C.C_CUSTKEY=O.O_CUSTKEY
group by C.C_NAME,C_CUSTKEY
HAVING sum(O_TOTALPRICE) > 0
